image: 
  file: Dockerfile
  
tasks:
  - name: workshop-astra-tik-tok
    before: |
      cd /workspace/workshop-astra-tik-tok 
      npm install
    command: |
      source ~/.bashrc
      echo "workshop-astra-tik-tok gitpod ready - LET'S DO THIS!"
      gp open README.md
      astra
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: open-preview
  - port: 3000
    onOpen: ignore    
